gnosis/dex-services

README.md
updating the most important file: the readme
=> updates Readme

driver/src/main.rs, driver/src/models.rs
finally got a rust linter installed
=> New linting

.travis.yml, event_listener/dfusion_db/snapp_event_receiver.py, event_listener/dfusion_db/tests/snapp_event_receiver_test.py, event_listener/requirements.txt
Adding basic unit tests for the existing receivers and making them part of CI
=> Unit tests for event receivers

event_listener/dfusion_db/models.py, event_listener/dfusion_db/snapp_event_receiver.py, event_listener/dfusion_db/tests/models_test.py
My refactoring broke the event receiver (which I discovered by running the e2e tests). This PR should fix the issues introduced.
=> [Easy] fix event receiver

driver/src/deposit_driver.rs, test/e2e-tests-deposit.sh
change the accounting
and the touched e2e test
=> fixing balance accounting and updating to new smart contracts

driver/src/contract.rs, driver/src/deposit_driver.rs, driver/src/lib.rs, driver/src/models.rs
1) Remove trivial assertion in test
2) adjust indentation (tabs -> spaces) in deposit_driver
3) don't panic in deposit_driver
4) inject db and contract (so that they can be mocked for unit tests)
=> [Driver] minor cleanups

driver/Cargo.lock, driver/Cargo.toml, driver/src/contract.rs, driver/src/db_interface.rs, driver/src/deposit_driver.rs, driver/src/error.rs, driver/src/models.rs, driver/src/withdraw_driver.rs
This adds basic unit tests for withdraw and deposit driver.
=> Creating mocks and testing withdraw_driver

event_listener/requirements.txt
Not 100% sure what happened last week, but it looks like our master branch started failing for no obvious reason (the build that broke it doesn't contain any python code).
This PR tries to fix it.
=> Trying to fix python build on master

event_listener/requirements.txt
master seems broken: https://travis-ci.org/gnosis/dex-services/jobs/513104295
=> [Easy] fix python build

.travis.yml, docker-compose.yml, docker/driver/Dockerfile, docker/event_listener/Dockerfile, docker/truffle/Dockerfile
This PR is trying to improve our build time by creating a higher cache hit ratio on travis.
=> [Travis] Better caching

driver/Cargo.lock, driver/Cargo.toml, driver/src/deposit_driver.rs, driver/src/lib.rs, driver/src/models.rs, driver/src/price_finding/error.rs, driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/mod.rs, driver/src/price_finding/price_finder_interface.rs, driver/src/withdraw_driver.rs
This PR adds an implementation of the price finding interface that calls into the linear optimization solver @twalth3r implemented in Python.
The component is doing the following steps:
1) Convert Orders/Balances into the json format the solver expects
2) Write json to disk
3) Invoke solver passing the json file that was written
4) Reading the result file into json
5) Converting the result file into solution struct (and storing prices in memory for next run)
I added a custom error class for PriceFinding, which should help debugging in the future (since we will be able to distinguish other error from solver related errors). Once used, that error should probably be wrapped into a DriverError.
I'm planning to add unit tests for the serialization/deserialization methods, but would suggest …
=> [Driver] PriceFinder that uses liner optimization solver

driver/src/contract.rs, driver/src/db_interface.rs, driver/src/models.rs
This PR exposes the contract and database functionality that is required to implement the order_listener.
Most of it is just adding boilerplate code similar to what we already have so please look out for copy/paste errors.
Thanks
=> [Driver] Adding contract/db functionality needed to process auctions

.travis.yml, test/e2e-tests-auction.sh, test/e2e-tests-deposit.sh, test/e2e-tests-withdraw.sh
Regarding issue #69
- Update contract code (to include sell-order.js script)
- Include 6 orders from workshop as example data for testing
- Wait for state transition (from auction settlement)
- Check and verify updated balances (or feasibility of results)
=> E2E Test Order Collection Event Listener

driver/Cargo.toml, driver/README.md, driver/src/bin/main.rs, driver/src/db_interface.rs
db_interface had a few errors pointed out by my IDE [intellij-rust](https://intellij-rust.github.io/). They were mainly the following 3 problems (2 of which are issues with the language support).
1. [actual error] trying to use public module (mongodb::bson)
2. `Client::connect` is detected a trait which is not in scope (NetworkConnector)
- Issue submitted to maintainers [here](https://github.com/intellij-rust/intellij-rust/issues/3654)
3. [False Positive] cannot move error for `*current_state_root`. This issue was identified and apparently solved [here](https://github.com/intellij-rust/intellij-rust/issues/3164)
=> [Linting] Some Errors

driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/price_finder_interface.rs
=> [Driver] LinearOptimisationPriceFinder unit tests

driver/src/deposit_driver.rs
refactoring with hopefully the same beauty as Felix's code
=> [Driver, Easy] Refactoring deposit_driver for readability

driver/src/deposit_driver.rs, driver/src/order_driver.rs, driver/src/util.rs, driver/src/withdraw_driver.rs, test/e2e-tests-auction.sh, test/e2e-tests-withdraw.sh
Self explanatory. E2E test should be passing.
=> Applying new contract logic (without empty 0th batch) in services

driver/src/contract.rs, driver/src/deposit_driver.rs, driver/src/order_driver.rs, driver/src/util.rs, driver/src/withdraw_driver.rs, test/e2e-tests-auction.sh, test/e2e-tests-deposit.sh, test/e2e-tests-withdraw.sh
As title. E2E test should be passing.
=> Adjusting driver to deal with 3 minute batch times instead of 20 blocks

driver/src/price_finding/naive_solver.rs, driver/src/price_finding/price_finder_interface.rs, test/e2e-tests-auction.sh
Closes #113 
**Test Plan**
Added unit test for solution encoding and adjusted e2e test with better documentation of what we are expecting to see.
Run both to make sure our demo is now working.
=> [Driver] fix solution encoding

driver/src/deposit_driver.rs, driver/src/models.rs, driver/src/order_driver.rs, driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/naive_solver.rs, driver/src/util.rs, driver/src/withdraw_driver.rs
=> Make State balances Private

README.md
Just an update to keep e2e-test file names correct.
=> [Easy] update readme for e2e-tests

.travis.yml, driver/src/bin/main.rs, driver/src/deposit_driver.rs, driver/src/lib.rs, driver/src/models/standing_order.rs, driver/src/order_driver.rs, driver/src/price_finding/price_finder_interface.rs, driver/src/util.rs, driver/src/withdraw_driver.rs
Closes #63 and #22. Include strict linting (for the purpose of improving our rust)
**Test Plan**
See that travis passes.
=> Clippy - Rust Linting 

.travis.yml, test/e2e-tests-deposit-withdraw.sh
Test Plan - see that Travis build is successful.
=> [Easy] Travis to fail whenever any test-script fails

driver/Cargo.toml, event_listener/dfusion_db/management/commands/run_listener.py
- just saw it on Felix PR
Sry for not doing that earlier.
=> updating authors alphabetically

dfusion_rust_core/src/models/account_state.rs, dfusion_rust_core/src/models/mod.rs, driver/src/db_interface.rs, driver/src/deposit_driver.rs, driver/src/order_driver.rs, driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/naive_solver.rs, driver/src/price_finding/price_finder_interface.rs, driver/src/withdraw_driver.rs, listener/src/event_handler/flux_transition_handler.rs, listener/src/event_handler/initialization_handler.rs
as title. It's a more expressive name than just state
Travis
=> [easy] State -> AccountState rename

driver/src/lib.rs
As rightfully suggested by @anxolin in #226 
`cargo check`
=> Pass traits

README.md, test/e2e-tests-auction.sh, test/e2e-tests-deposit-withdraw.sh, test/e2e-tests-standing-order.sh
This PR is the relevant services update for https://github.com/gnosis/dex-contracts/pull/195
CI
=> Update scripts and adjust e2e tests to use named arguments

dfusion_rust_core/src/models/account_state.rs, dfusion_rust_core/src/models/flux.rs, dfusion_rust_core/src/models/mod.rs, dfusion_rust_core/src/models/order.rs, driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/price_finder_interface.rs
Since stableX supports up to 2**16 tokens
CI
=> [Refactor] Change token datatype from u8 to u16

docker/README.md, docker/rust/Dockerfile, docker/rust/base/Dockerfile
As title. Also updating the images to not be based on my personal dockerhub account.
Travis
=> Adding a docker readme

driver/src/price_finding/naive_solver.rs, driver/src/price_finding/price_finder_interface.rs
As title and per offline discussion
Travis
=> [Easy] rename fee.percentage to fee.ratio

.travis.yml, test/setup_contracts.sh
Goal of this PR is to make the e2e tests from the previous PRs run continuously on travis
See demo run in travis
=> Stablex travis

.travis.yml
=> Try to fix master

dfusion_rust_core/src/database/mod.rs, dfusion_rust_core/src/lib.rs, dfusion_rust_core/src/models/account_state.rs, dfusion_rust_core/src/models/solution.rs, dfusion_rust_core/src/models/standing_order.rs, driver/src/bin/dfusion.rs, driver/src/bin/stablex.rs, driver/src/contracts/base_contract.rs, driver/src/contracts/snapp_contract.rs, driver/src/contracts/stablex_auction_element.rs, driver/src/contracts/stablex_contract.rs, driver/src/driver/deposit_driver.rs, driver/src/driver/order_driver.rs, driver/src/driver/stablex_driver.rs, driver/src/driver/withdraw_driver.rs, driver/src/lib.rs, driver/src/price_finding/linear_optimization_price_finder.rs, driver/src/price_finding/price_finder_interface.rs, driver/src/util.rs, listener/src/event_handler/auction_settlement_handler.rs, listener/src/event_handler/deposit_handler.rs, listener/src/event_handler/flux_transition_handler.rs, listener/src/event_handler/initialization_handler.rs, listener/src/event_handler/order_handler.rs, listener/src/event_handler/standing_order_handler.rs, listener/src/event_handler/util.rs, listener/src/event_handler/withdraw_handler.rs, listener/src/link_resolver.rs, listener/src/main.rs, listener/src/runtime_host.rs
as suggested in #271 
It compiles on Travis.
=> [Easy] remove extern crate

package-lock.json, test/e2e-tests-stablex.sh
This may not actually need to be merged (and shouldn't until the related branch has been merged to master).
This relates to [dex-contracts:pull275](https://github.com/gnosis/dex-contracts/pull/275) and will be used to make any repairs that the contract changes may impose
Closes #278
=> Set contracts to 4 minute batch PR and check for breaking changes.

driver/src/price_finding/linear_optimization_price_finder.rs
#302 removed execUtility from the linear solver JSON but left it in some test cases, this just cleans it up.
Unit tests still pass
=> [Easy] Clean Linear Solver JSON Deserialization Test Cases

.travis.yml
Hoping to speed up the build and unit test step
=> Use sccache

docker/deploy.sh
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FLN6AfV6TxxJtu%2Fgiphy.gif&token=style" data-gitmeme-token="style"><img src="https://media0.giphy.com/media/LN6AfV6TxxJtu/giphy.gif" title="Created by gitme.me with /style"/></a>
=> [Trivial] fix indentation of curl command

.travis.yml
self explanatory. This line will upgrade the version of the solver that we use. @marcovc should we directly upgrade to the version that contains your fix as well?
CI
=> [Easy] Upgrade solver version

.travis.yml
This should hopefully fix the ongoing alerts on master/mainnet.
Observe if assumption above is true.
=> [Easy] Bump Solver

driver/src/price_finding/linear_optimization_price_finder.rs
Closes #429.
This should be merged after the solver is bumped to a version >= 0.5.4. This should make travis happy.
@fleupold Please make sure there are no other places calling the solver. Thanks!
=> Updates solver call

.travis.yml
=> [Trivial] Bump solver version

hooks/pre-commit, hooks/pre-push
Will attempt to give these a try before requesting review.
**Test Plan:**
Run commands
```sh
cp hooks/pre-* .git/hooks/
chmod +x .git/hooks/pre-commit
chmod +x .git/hooks/pre-push
```
Then try to commit and push some bad (unlinted, unformated code).
=> These hooks were outdated

Cargo.lock, driver/Cargo.toml, driver/src/error.rs
=> [Easy] Remove ethabi crate as it is no longer used

.travis.yml
=> [Trivial] Bump solver to v0.5.7

.travis.yml
=> [Trivial] Bump solver to v0.5.8

driver/src/driver/deposit_driver.rs, driver/src/driver/order_driver.rs, driver/src/driver/withdraw_driver.rs
Some of the logs occur too frequently and provide no-so-valuable information. I have thus made moved them into debug, for less noise pollution.
=> [Easy] Info to Debug

.travis.yml
Attempting to consolidate local tests into a single Travis "stage".
Closes #474
Test Plan: Check that all expected tests are included in travis build.
=> Improved CI

Cargo.lock
=> [Trivial] Bump hex from 0.4.0 to 0.4.1

README.md
Please do not approve this PR. It is a test to see if `merge-when-green` label can override the approval.
=> Include table of contents in README

README.md, driver/src/contracts/mod.rs, driver/src/contracts/stablex_auction_element.rs, driver/src/contracts/stablex_contract.rs, driver/src/main.rs, driver/src/orderbook/batched_auction_data_reader.rs, driver/src/orderbook/mod.rs, driver/src/orderbook/paginated_auction_data_reader.rs
This reverts the revert of #484 . There is a second commit after the revert commit which fixes the problem and adds another unit test.
I will attempt to run this locally against mainnet to verify that is picking up all orders.
=> Batched orders again

driver/src/orderbook/paginated_auction_data_reader.rs, driver/src/price_finding/optimization_price_finder.rs
In relation to solver issue https://github.com/gnosis/dex-solver/pull/129#issuecomment-585201068
=> [Easy] Token representation

driver/src/price_finding/naive_solver.rs
fixes #520 
Test Plan:
CI passes and added more unit tests for this issue.
=> Fix naive solver panic

Cargo.lock
=> [Easy] Bump memchr version to v2.3.2

driver/src/driver/scheduler/system.rs, driver/src/main.rs
Simply removing the substring "error" from the success log for solution submission as it pollutes the Kibana logs
=> Easy log update

.travis.yml
Some improved rounding comes with it...
=> [Easy] standard-solver bump

.travis.yml
=> solver bump

driver/src/orderbook/streamed/orderbook.rs
By default the event based orderbook returns balances for users even
when the user does not have an order with that token. The other
orderbooks don't do that which confuses the shadowed orderbook diff.
=> Filter account states in event based orderbook

driver/src/orderbook/streamed/state.rs
Tests if there are any issues in case the same order is used for multiple trades in the same solution. No changes to the code are needed to make the test work.
```
cargo test orderbook_solution_touching_same_order_twice
```
=> Test splitting order into two trades in the same solution

.travis.yml, driver/src/price_finding/price_finder_interface.rs
[Optional] 
Fixes #909 
This integrates a major refactoring of the standard solver. While the logic was not changed, many code components were changed.
non
=> New solver refactoring

.travis.yml, README.md, docker-compose.best-ring-solver.yml, driver/src/main.rs, driver/src/price_finding/price_finder_interface.rs
In order to improve the robustness of our solver fleet, we want to battle best the best-ring solver, which can unblock the standard-solver, in case it finds only solutions with negative utilities.
This PR introduces best-ring-solver.
This is only a very simple introduction, I have not forgotten your requests for a simple solver interface, but this one should first be discussed here https://github.com/gnosis/dex-solver/issues/259
CI
=> Introducing the 'best-ring-solver'

pricegraph/src/orderbook.rs
Just `s/transient/transitive` to correct some of the language.
=> [Trivial/Pricegraph] Rename transient to transitive

.travis.yml
solver PRs included:
* direct solver interface
* suppress solver log for log levels > INFO
e2e tests
=> Update solver version to v0.8.0

.travis.yml
Solver PRs included:
* forbid self-trades via combinatorial constraints (https://github.com/gnosis/dex-solver/pull/306)
* alternative MIP-based ring-finder for best-ring solver (only added, not used currently)
* code cleanup
e2e tests
=> Update solver version to v0.8.1

README.md
This PR just fixes the README `driver` help to match the current output.
=> fix README help

.travis.yml
=> Bump open solver to v0.1.1
