- docker-compose.yml
We should be able to run all parts of our system by running a simple `docker compose up` command. This change creates the docker compose file and adds the first subsystem (mongodb) which doesn't require any customization. 
I'd hope that the event_listener and driver could be separate docker containers that will all be launched and connected with this docker compose file.
This is also how trading-db handles their subsystems.
> [Easy] Adding simple docker-compose

- README.md
- docker-compose.yml
- test/e2e-tests-deposit.sh
This will give us an easy to use a UI to inspect the current state of the database.
Run `docker-compose up`, visit [http://localhost:3000/](http://localhost:3000/), connect to the default database. On the left side bar, under Connections select accounts and execute query - notice initial account state.
Run e2e test from shell. Re-execute query in UI and observe that we now have three state updates.
> Adding a Mongo UI to docker-compose

- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
Addresses #34
Upon processing withdraws, we mark them as being valid if their account balance was reduced.
To test, we can run the e2e test and afterwards run:
```
> mongo dfusion2 --eval "db.withdraws.find()"
{ "_id" : ObjectId("5c6d8008049883000f400164"), "accountId" : 3, "tokenId" : 3, "amount" : 18, "slot" : 1, "slotIndex" : 0, "valid" : true }
```
> [EventListener] Expose valid flag on withdraw record

- driver/Cargo.lock
- driver/Cargo.toml
- driver/src/contract.rs
- driver/src/db_interface.rs
- driver/src/deposit_driver.rs
- driver/src/error.rs
- driver/src/models.rs
- driver/src/withdraw_driver.rs
For use in Mock framework the return types have to be cloneable, which a generic error isn't. Also introducing a kind makes it easier to test, we are failing for the "right" reason.
> Refactoring Error to be package specific type for better unit testing

- docker-compose.yml
- driver/src/deposit_driver.rs
- driver/src/models.rs
- driver/src/withdraw_driver.rs
Rust naming convention suggests snake_case for its struct members. We originally chose to use CamelCase, because the event listener inputs events using CamelCase keys into the database and we couldn't find a simple way to parse the json into native rust objects if the keys didn't exactly match.
Turns out there is a simple macro for it: Using `#[serde(rename_all = "camelCase")]` will make snake case member variables work and parse from and to CamelCase objects.
🎈
> [Driver] Renaming State and Flux members to snake case

- .travis.yml
We are currently building twice for each pull request (once because it's a PR and once because of the branch matching rule).
This PR adds a line to the travis file that prevents it from building on every branch. This should reduce the build time per PR in half.
Thanks @luarx for pointing this out.
> [Easy] Only run one build per PR

- .gitignore
- .ssh/.gitignore
- docker-compose.yml
- docker/driver/Dockerfile
- docker/driver/clone_solver.sh
- docker/solver/Dockerfile
- driver/Cargo.toml
This PR adds @twalth3r solver codebase tot he driver Docker image, if the driver is built with 
```
docker-compose build --build-args use_solver=1 driver
```
It then assumes to find ssh keys inside `dex-services/.ssh` which have permissions to read the batch auction repo (need to be whitelisted in some account that has read access first). 
The build file then clones the repo and installs the dependencies. 
Successful installation can be checked by running:
```
docker-compose run driver bash -c 'cd ../batchauctions/src && python main.py @input/run_single_docker.cfg'
```
This should show solver output.
In order to run the solver we need to download/install SCIP and Gurobi. Since those dependencies don't update very often I pulled them into a separate Docker image which will have to be …
> [Driver] conditionally include solver to Docker setup

- docker/driver/Dockerfile
- docker/solver/Dockerfile
- driver/Cargo.lock
The docker base image used to be >500MB in v1 (https://cloud.docker.com/repository/docker/fleupold/dfusion-solver-base/tags). 
This means on every travis run, we download 500MB to build our driver image. After learning a bit about docker (https://www.youtube.com/watch?v=vlS5EiapiII), I wrote this PR to try to minimize the size of this image.
New image size is 85MB.
> [Docker] minimize the size of the solver base image

- driver/src/lib.rs
- driver/src/models.rs
- driver/src/price_finding/mod.rs
- driver/src/price_finding/price_finder_interface.rs
This PR defines a rust interface that the order_processor will interact with to invoke the solving engine. The solving engine can be implemented in different ways
1. Mocked (for unit tests)
2. Simple Solver (#58)
3. Tom's sophisticated solve (#59)
Let's discuss the interface and data structures here. I included the mock implementation so that we can start using this interface.
Addresses #57
> [Driver] Defining an interface for the driver<->solver interaction

- driver/src/contract.rs
- event_listener/config/settings.py
- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/generic_event_receiver.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/models_test.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
This is currently working as expected, with Model and Receiver Tests. To try for yourself, 
```
docker-compose up
truffle exec scripts/sell_order.js 1 1 2 1 2
```
Watch the container for the following message...
```
listener_1     | [INFO] [MainProcess] SellOrder received {'auctionId': 1, 'slotIndex': 0, 'accountId': 1, 'buyToken': 1, 'sellToken': 2, 'buyAmount': 1, 'sellAmount': 2}
listener_1     | [INFO] [MainProcess] Successfully included Order - 5c9cd4ed2ce8ce000c70aaa8
```
> #55 Order Event Listener

- .travis.yml
As title.
Addresses one of the points suggested in #61
> [Easy] Don't launch unnecessary docker images on travis

- driver/src/bin/main.rs
- driver/src/contract.rs
- driver/src/models.rs
Im just getting comfortable with the rust code so that I can start writing the simple solver and e2e-test for running an auction.
There were a few warnings and errors that my IDE brought up while I was reading through. The lest obvious one was the implementation ordering of the SnappContract trait (which warned should be in the same order as declared). 
Another place where my IDE provides a very strict warning is here is in `driver/src/contract.rs`
https://github.com/gnosis/dex-services/blob/b43e7dae6c48e4f3c9df115ca506257b41c32ccc/driver/src/contract.rs#L165-L166
Where it says "cannot assign field of immutable binding". The IDE suggested to make the opt mutable, so I have... Please let me know if this is alright with ya'll.
> [Easy] Typos, Indentation, Rust warnings etc

- .travis.yml
- driver/src/db_interface.rs
- driver/src/models.rs
- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit.sh
- test/e2e-tests-withdraw.sh
1. Event Listener to write Strings to DB for all "large integers" (i.e. > 64 bits). Only change required here is to update the `to_dictionary` function for each model (since these dictionaries are what is written to the DB). Its really nice that we don't have to change the model definitions!
2. Driver will have to implement a different `from` method as which parses these amounts as strings
> #83 - Store all large integers in DB as string

- docker-compose.yml
Silencing less important containers and slightly more favourable volume sharing (making sure driver and truffle always use the same contract base)
> [Easy] Small docker-compose improvements

- docker-compose.yml
- docker/truffle/Dockerfile
Our new logic for ensuring that the contracts within truffle are the same as the current contracts, was overwritting run.sh of the truffle docker.
This was not spotted in the tests, as the tests do not rely on the truffle docker image and do their own migration.
Hope you guys have suggestions for prettier solutions than mine.
> [Fix] Stopping overwritting run.sh

- event_listener/dfusion_db/generic_event_receiver.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/models_test.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
- test/e2e-tests-deposit.sh
- Listener should receive Auction Settlement Event, store it in the DB, and update account balances according to the `pricesAndVolumes` emited as part of the event. This involves implementation of
- Auction Settlement model (with same attributes as the event)
- to and from dictionary for DB storage
- serialize solution (byte array to prices and trade executions)
- update balances based on Orders and auction results
> [Listener] Auction Settlement

- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/models_test.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
Previously, there was a silly `serialize_solution` (meant to be `deserialize_solution`) function inside the Auction Settlement class which was being called every time we wanted to access the solution in a "human readable format". More naturally, it should be converted into an Auction Result object immediately upon the event emission.
This involved some changes to the unit testing, but overall makes for a much easier Listener environment. 
Note that this will likely conflict with changes found in branch #98, but these can be resolved at a later state.
> [Listener] Use Result object as solution attribute of Settlement

- docker/driver/Dockerfile
- driver/src/bin/main.rs
- driver/src/lib.rs
- driver/src/order_driver.rs
- driver/src/price_finding/mod.rs
In case we build docker with `--build-arg use_solver=1`, this PR will make it so that we use the sophisticated solver. In all other cases (e.g. travis) we will use the naive solver.
> Reading from an ENV var and deciding which solver to use

- .travis.yml
- docker/driver/Dockerfile
- docker/driver/base/Dockerfile
- docker/event_listener/Dockerfile
- docker/event_listener/base/Dockerfile
Extracting code independent base configuration for docker images into a separate images, which I pushed to docker hub.
Ideally this should reduce the amount of time travis takes to build our containers.
> Creating base images to improve build times

- driver/src/bin/main.rs
- driver/src/contract.rs
- driver/src/db_interface.rs
- driver/src/deposit_driver.rs
- driver/src/lib.rs
- driver/src/models.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/withdraw_driver.rs
Full report of `clippy` warnings can be found here
https://gist.github.com/bh2smith/af26bb187b1d1dbc1dc3f1963ac84052
Brief summary (i.e. some highlights) of those most commonly fixed
- warning: redundant closure found
```
| .map_err(|e| DriverError::from(e))
|          ^^^^^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `DriverError::from`
```
- writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
```
| fn serialize_balances(balances: &Vec<u128>, num_tokens: u8) -> serde_json::Value {
|                                 ^^^^^^^^^^ help: change this to: `&[u128]`
```
- warning: length comparison to zero
```
| if docs.len() == 0 {
|    ^^^^^^^^^^^^^^^ help: using `is_empty` is clearer and more explicit: `docs.is_empty()`
```
- …
> [Lint] Several clippy warnings by suggestion

- driver/src/deposit_driver.rs
- driver/src/models/state.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/withdraw_driver.rs
I didn't like that our models "know" (as in import a dependency) about how the price finding decides to serialize account balances when it passes input data to the python solver (by exposing the ought to be private `accountId` and `tokenId` methods). This is an implementation detail to the linear optimization solver that should not be leaked to the basic data model.
I also didn't like that `State` had to know about `Solution` (in order to update balances it took a reference to the `Solution` object). While we could argue that `Solution` is a basic data model that should be moved into the models submodule (instead of being in price_finding as it is right now), there is no need for the two to be coupled. `update_balances` can be a free method on the order_processor, which already has to …
> [Driver] Making sure our models don't know about price finding internals

- driver/src/deposit_driver.rs
- driver/src/models/mod.rs
- driver/src/models/order.rs
- driver/src/models/state.rs
- driver/src/order_driver.rs
- driver/src/withdraw_driver.rs
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit-withdraw.sh
Currently two state roots with the same balances will have the same hash. This can introduce problems as in our data-model we are only filtering by hash in our query and not by the state_index.
One way to solve this is to introduce a nonce into the hash (this way the state_index is part of the entropy of the hash).
Alternatively we could also query both the currentStateRoot as well as the current stateIndex from the smart contract and filter for a combination of state_index and state_hash. However this would require another contract call each time we query for balance state.
One disadvantage of the proposed approach is that the hashes in our e2e tests now depend on the state_index that they'd been applied on. This means that changing the order of the tests or adding another test, might …
> [Driver] Adding a nonce to the state hash

- .travis.yml
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit-withdraw.sh
I'm not entirely sure if this is a much better approach, since it requires a lot of thinking on which commands need to be retried and which ones don't.
Yet, it will make sure that we are not waiting unnecessarily and also not subject to flaky timing issues.
Looking forward to a discussion...
**Testplan**
Install retry and run e2e tests locally:
```
brew pull 27283
brew install retry
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile
./test/e2e-tests-deposit-withdraw.sh && ./test/e2e-tests-auction.sh
```
Closes #100
> [E2E] replacing sleep with retry statement

- event_listener/requirements.txt
Turns out Django 2.1.0 - 2.1.6 have a moderate security vulnerability, This change should make the  [warning](https://github.com/gnosis/dex-services/network/alert/event_listener/requirements.txt/django/open) go away.
> [Easy] Update django version to address security warning

- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
As title. This PR also updates the contracts to use the most recent version.
```
git submodule update
rm -r build
truffle build
cd ../
docker-compose build truffle
docker-compose up
```
Open localhost:3000 in a browser and see that constants table has new entries.
> [Listener] Write init constants to DB

- .pep8
- .travis.yml
- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
- event_listener/requirements.txt
- pylintrc
This PR makes it so that linter errors are actually going to break travis. I went ahead and created config files for both pep and pylint. @bh2smith feel free to add whatever rules your IDE thinks we should enforce.
This makes it so that we don't regular cleanup diffs by our [Putzfee](https://bilder.kalaydo.de/kalaydo/images/2018/11/04/16/aaa68d0d/medium_image_0.jpg?lastModified=1541346025000) but instead can encourage everyone to only submit clean code in the first place.
```
pep8 --config .pep8 event_listener/dfusion_db/
pylint --errors-only event_listener/dfusion_db/
```
> [Listener] enforce proper linting

- .travis.yml
- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/generic_event_receiver.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/snapp_event_receiver.py
- event_listener/dfusion_db/tests/models_test.py
- event_listener/dfusion_db/tests/snapp_event_receiver_test.py
- test/e2e-tests-standing-order.sh
This PR contains logic for processing *StandingSellOrderBatch* events. It depends on https://github.com/gnosis/dex-contracts/pull/97 and assumes that the order details are emitted as blobs.
For now it relies on unit tests to ensure functionality is correct.
Once depending PR is landed, update submodule and run placeStandingOrder script. Observe that standing orders are added to the database.
> [Listener] processing StandingSellOrderBatch events

- event_listener/dfusion_db/database_interface.py
- event_listener/dfusion_db/models.py
- event_listener/dfusion_db/tests/models_test.py
When computing the updated balances after auction settlement, we now also need to consider the standing orders that were valid at the given time.
Unit test + e2e test in next PR
> [Listener] Consider standing orders when computing balance after AuctionSettlement

- driver/Cargo.lock
- driver/Cargo.toml
- driver/src/contract.rs
- driver/src/error.rs
- driver/src/models/mod.rs
- driver/src/models/state.rs
This reverts commit deecfe1b246b75142628527a95d7fa3d47fa6167, as new  version 0.7 seems to have an error
> Revert "Modifications for new web3 lib (#143)"

- test/e2e-tests-standing-order.sh
Adjusting the e2e test to make sure
a) Standing ordered gets carried over in full (getting matched again even if matched before)
b) Standing order can be canceled after which it will no longer get matched.
> [e2e] update standing order test with full logic

- driver/src/bin/main.rs
- driver/src/lib.rs
- driver/src/order_driver.rs
- driver/src/util.rs
Removing a bunch of 
```
warning: trait objects without an explicit `dyn` are deprecated
```
on the newest rust version.
Compile without warnings.
> [Easy] adding dyn infront of trait types

- .gitignore
- README.md
1. `truffle compile` will use global install - `npx truffle compile` uses local version correctly (my install was failing)
2. added `.history` to `.gitignore` for users using it in VS
> David-Fix: README & .GITIGNORE

- .travis.yml
We are mainly interested in studying the docker logs after travis failures (as we seem to have some flakyness in our e2e tests which we should resolve). At the moment (e.g. https://travis-ci.org/gnosis/dex-services/jobs/559987321) we don't see the logs after failure.
> [Easy] showing docker compose logs after failure

- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/mod.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/standing_order.rs
- dfusion_rust_core/src/models/state.rs
- driver/src/deposit_driver.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/withdraw_driver.rs
I noticed that the datatypes we use in our rust models and the datatypes used in the events that the smart contract emits are different. This PR attempts at unifying the two data models.
compilation and rust unit tests.
> Refactor data types in rust models to make them consistent with SC

- listener/src/event_handler/mod.rs
- listener/src/main.rs
- listener/src/runtime_host.rs
This PR implements an interface which each event handler (e.g. Deposit, Withdraw, etc.) will implement. It also implements the RustRuntimeHandler which takes the events that are supposed to be processed according to the subgraph definition and forwards them to the specific event handler.
The next PR will implement the first concrete EventHandler (listening to Deposit events).
In one console run:
```sh
docker-compose down && docker-compose up graph-listener
```
In another one run:
```sh
truffle migrate
truffle exec scripts/setup_environment.js
truffle exec scripts/deposit.js 1 1 1
```
Observe the following print statements (and that the process no longer crashes)
```
INFO Received event, block_hash: ...
WARN Unhandled event with topic 0xba69…11ee, block_hash: ...
```
> [The Graph] Implementing a runtime to route events to specific handlers

- .travis.yml
- test/e2e-tests-deposit-withdraw.sh
We still don't see the error logs when a travis build fails (e.g. https://travis-ci.org/gnosis/dex-services/jobs/560457456).
This is critical to find the reason for our flakyness. I believe that the reason could be the `set -e` command inside the script, which I assume makes travis immediately stop the build and all future commands.
Running an expectedly failing build to verify.
> Remove `set -e` in travis script

- .travis.yml
- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/state.rs
- dfusion_rust_core/src/models/util.rs
- listener/src/event_handler/initialization_handler.rs
- listener/src/event_handler/mod.rs
- listener/src/runtime_host.rs
- listener/subgraph_definition/dfusion
- listener/subgraph_definition/schema.graphql
- test/e2e-tests-deposit-withdraw.sh
This PR adds a new Graph handler for the SnappBase initialisation event. It creates the genesis state and writes it into the graph database.
In one terminal run:
```
docker-compose down && docker-compose up graph-listener
```
In another terminal run:
```
truffle migrate
```
See how the event is being handles in the log statements. To verify go to localhost:8000 and run the following query:
```graphql
query {
accountStates {
id
numTokens 
balances
} 
}
```
> [The Graph] Adding Initialization event listener

- dfusion_rust_core/src/models/state.rs
- driver/src/deposit_driver.rs
This PR moves the logic of applying deposits into the shared library (more particularly into the State data model). This is to allow logic sharing between the driver and the listener.
Just travis, since no functionality changed.
> Moving applyDeposit into shared library

- .travis.yml
- Cargo.lock
- README.md
- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/mod.rs
- dfusion_rust_core/src/models/state.rs
- dfusion_rust_core/src/models/util.rs
- listener/Cargo.toml
- listener/src/event_handler/deposit_handler.rs
- listener/src/event_handler/flux_transition_handler.rs
- listener/src/event_handler/initialization_handler.rs
- listener/src/event_handler/mod.rs
- listener/src/event_handler/util.rs
- listener/src/main.rs
- listener/src/runtime_host.rs
- listener/subgraph_definition/dfusion
- test/e2e-tests-deposit-withdraw.sh
Apologies for the large PR, I already extracted the reorg of driver logic into the shared library in a separate PR but it still turned out quite big. I guess I could factor each of the things that's going on here into separate PRs which by themselves wouldn't make a ton of sense. Let me know if you prefer that.
What's going on here?
1. We register the event and event handler
2. We provide conversion methods to parse an Entity (read result from the GraphStore) into the respective data models (State, PendingFlux)
3. We implement the FluxTransitionHandler for deposits (withdraws will be handled later)
4. Unit + E2E tests
Run the docker-compose in one terminal. Run the `e2e-tests-deposit-withdraw.sh` in another (after `truffle migrate`). At the end run the following query in the graphiql …
> [TheGraph] applyDepositHandler

- .travis.yml
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit-withdraw.sh
- test/e2e-tests-standing-order.sh
- test/restart-containers.sh
- test/utils.sh
At the moment our E2E tests have a pretty messy output and it's hard to tell why and in which step a test is failing.
This PR makes it so that each command in an e2e test has en explicit description of its purpose (at the moment this is already the implicitly the case with comments inside the bash script).
The e2e test will then run all steps, printing their description with a ✅ if successful and printing it with a ❌ plus the error message and other output if not successful.
This should hopefully make it easier to see where in the tests we are having a problem.
As a side effect we also get rid of the external retry binary we had been using.
Check out travis for hopefully pretty prints
> [E2E Tests] Improving print statements for easier debugging

- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/util.rs
- listener/src/event_handler/flux_transition_handler.rs
This PR refactors various utility methods, which we defined over the course of the last days to use traits that can be implemented on the underlying data types (rather than naming the functions slightly different).
First, this is a more rusty way of organizing helpers and secondly it increases type safety. Take for example the `to_value` function.
At the moment this was implemented for any T that implements to_string (e.g. U256 & H256). Under the hood it would convert the variable into a Value of subtype BigDecimal (cf. all options [here](https://github.com/graphprotocol/graph-node/blob/792735ffdfa685c9bbec565b4e3802e35f7f0690/graph/src/data/store/mod.rs#L134)).
While this is fine for U256, H256 should instead be converted into a hex formatted string.
Making `to_value` a trait function …
> [easy] refactor util functions into traits

- listener/src/event_handler/mod.rs
- listener/src/event_handler/withdraw_handler.rs
- listener/src/runtime_host.rs
- listener/subgraph_definition/dfusion
- listener/subgraph_definition/schema.graphql
- test/e2e-tests-deposit-withdraw.sh
Closes #197 
It worked! Purpose of this PR is to get the withdraw requests into the graph listener!
**Test Plan:**
In one terminal run:
```
docker-compose down && docker-compose up graph-listener
```
In another one run:
```
truffle migrate
truffle exec scripts/setup_environment.js
truffle exec scripts/request_withdraw.js 1 1 1
```
Watch the logs for the following:
```
graph-listener_1  | Jul 27 01:01:30.973 INFO Processing Withdraw PendingFlux { slot_index: 0, slot: 0, account_id: 1, token_id: 1, amount: 1000000000000000000 }, block_hash: 0x1012e3332887b81c8d8076d046f89ab0fe2f50a80d894271a225e76fb9d22f2b, block_number: 38, subgraph_id: dfusion, component: SubgraphInstanceManager
```
or open a browser at `localhost:8000` and type the following query:
```
query {
withdraws …
```
> [TheGraph] Withdraw Listener

- dfusion_rust_core/src/models/account_state.rs
- driver/src/withdraw_driver.rs
- test/e2e-tests-deposit-withdraw.sh
The is a Pre-step to ensuring the event listener processes state transitions for withdrawals. 
**Test Plan**
End-2-end tests not breaking should suffice here.
> Migrate apply_withdraws into dfusion core

- .travis.yml
- test/restart-containers.sh
Seeing a lot of e2e tests fail because ganache is not yet started (after 1s sleep). 
E.g. https://travis-ci.org/gnosis/dex-services/jobs/565485559
This was introduced in #196 as we got rid of the retry library that was used before. This PR introduces are tool that allows waiting for a port to open (with timeout in ms).
See travis pass and be no longer flaky.
> [E2E Test] wait up to 30s for ganache to open port

- test/e2e-tests-auction.sh
Our current e2e tests are flaky. E.g. check out https://travis-ci.org/gnosis/dex-services/jobs/566931767#L1801 which failed, but re-running it without a change succeeded.
- Reason for the fail was that the solution of applyAuctions only provided 0 executed buy/sell Volume.
- Reason for that is that the stateBalances for all participants were 0 (thus not sufficient balance to make any trade)
- Reason for that is that the deposits hadn't been correctly applied (cf. the temporary `deposit_driver transport error` in line 1794). 
These errors can happen from time to time and a more sophisticated retry strategy in such cases is probably needed. However, the fundamental problem is that deposit application and auction application happen in the same driver runloop.
This PR makes it so that we wait …
> [E2E] fix a flaky test

- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/standing_order.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- test/restart-containers.sh
Branched off of (now closed) #202 
Closes #203 
As suggested in #203, make `slot` and `slot_index` (optional props) into an optional struct named `batch_information` instead
Fixes tests
> 206: Slot & Slot Index >> Batch Information optional struct

- test/restart-containers.sh
Restarting the containers using `test/restart-containers.sh` script won't restart services like `graph-listener`.
Modified the script so all services are restarted, so it takes for example the new mappings/handlers for graph-listener
> Restart all services in restart-containers.sh

- README.md
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit-withdraw.sh
- test/e2e-tests-standing-order.sh
The services depends on truffle and other dependencies being install globally.
Truffle can have different versions depending on the project, so it's better not to rely on the global truffle and use npx instead.
> Use npx for truffle instead of global system one

- .travis.yml
- Cargo.lock
- Cargo.toml
- docker/rust/Dockerfile
- graph_node_reader/Cargo.toml
- graph_node_reader/src/entities.rs
- graph_node_reader/src/filter.rs
- graph_node_reader/src/lib.rs
- graph_node_reader/src/sql_value.rs
- graph_node_reader/src/store.rs
At the moment, the only way to interact with the low level postgres representation from The Graph is via the [Store trait](https://github.com/graphprotocol/graph-node/blob/master/graph/src/components/store.rs#L650).
This trait is very elaborative in that it not only handles both read and write operations, it also covers both chain related storage as well as entity related storage.
The only thing we are interested on the driver side (and long term also on the listener side) is to read Entities. This means, we don't want to setup the entire dependency graph that the main graph component requires (GQL adapter, ethereum adapter, etc), but instead want to be able to instantiate a reader component just from a postgres connection (with a read-only user).
This PR takes the large store component …
> GraphNode reader

- dfusion_rust_core/src/database/mod.rs
- driver/src/deposit_driver.rs
- driver/src/mongo_db.rs
- driver/src/order_driver.rs
- driver/src/withdraw_driver.rs
This PR adds a method to obtain the AccountState by state index (previously only possible by state root). This is needed in the listener whenever we apply a state transition.
I also cleaned up the interface to use the full width U256 instead of using only the low u32 of our slot/state index.
CI
> Minor changes to the db interface

- Cargo.lock
- dfusion_rust_core/Cargo.toml
- dfusion_rust_core/src/database/graph_reader.rs
- dfusion_rust_core/src/database/mod.rs
- dfusion_rust_core/src/lib.rs
- dfusion_rust_core/src/models/util.rs
- listener/Cargo.toml
- listener/src/event_handler/flux_transition_handler.rs
- listener/src/event_handler/util.rs
- listener/src/main.rs
- listener/src/runtime_host.rs
This PR implements the DBInterface trait for the postgres backed graph reader. Once fully implemented, the driver should be able to switch from MongoDB to Postgres DB by just instantiating the other implementation [here](https://github.com/gnosis/dex-services/blob/master/driver/src/bin/main.rs#L18).
For now, I'm using this component in the existing graph listeners that are reading state from the database. I'd hope we can use the same component in the AuctionApplication handler that @bh2smith is working on. This will require finishing the two remaining unimplemented methods.
Make sure E2E tests covering the exiting graph listeners are still running. 
Also, for withdraw & deposit tests we can already make the adjustment outlined above and have the driver use the graph listener instead of …
> [The Graph] Postgres db interface implementation

- Cargo.lock
- dfusion_rust_core/src/models/mod.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/solution.rs
- dfusion_rust_core/src/models/util.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/mod.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
#220 is introducing a new data type - AuctionResults. Really, this should be reusing the existing solution struct. The struct already defines how it is serialized into a bytes array and only misses the inverse deserialize method.
However, at the moment this struct only available in the driver project.
This PR moves the struct into the shared core library and implements the deserialization method (including a unit test)
CI and make sure the deserialize method can be used in #220
> Move Solution into shared models library

- test/e2e-tests-deposit-withdraw.sh
- test/e2e-tests-standing-order.sh
#227  (more specifically https://github.com/gnosis/dex-services/commit/248554708b8e5b85a4afcbc12646fa1f6ee5e7e3#diff-0085bcc75915940251129aadc6ef5004) remove a few assertions in the standing order e2e test for which we had no The Graph equivalent.
This PR re-adds those assertions.
> Re-add deleted e2e test assertions

- .travis.yml
- test/restart-containers.sh
Restarting the containers between tests takes ~60s at the moment (cf. https://travis-ci.org/gnosis/dex-services/jobs/578335529#L530)
With this change I was able to reduce the time between restarts to <15s. This should lead to a speedup of ~1.5mn for our overall travis time.
Observe restart-container.sh timing in travis.
> Using docker-compose kill to speed up restarts

- dfusion_rust_core/src/database/graph_reader.rs
- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/standing_order.rs
- driver/src/contract.rs
- driver/src/deposit_driver.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/util.rs
- driver/src/withdraw_driver.rs
- listener/src/event_handler/auction_settlement_handler.rs
- listener/src/event_handler/flux_transition_handler.rs
- listener/src/link_resolver.rs
- listener/src/runtime_host.rs
This PR fixes a bunch of clippy suggestions which are not land blocking (since they are minor). More specifically:
- trait objects without an explicit `dyn` are deprecated
- &vec![...] == &[...]
- complex types in mocks should be extracted (typedef)
- new methods without arguments should be implemented via Default trait
- don't use clone on copy types
> [Easy] misc clippy fixes

- dfusion_rust_core/src/models/account_state.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- listener/src/event_handler/auction_settlement_handler.rs
We currently represent balances inside the AccountState model as a continuous array with values in the form of 
```
acc1_token1, acc1_token2, ... acc1_tokenN, acc2_token1 ..., accM_tokenN
```
While this works well for a small number of accounts, this doesn't scale to the new dfusion model, where our address space is 256 bits. 
The number of participants in a batch is upper bound by the number of orders in a batch. We only need to pass the balances to the solver of accounts that are participating in the current auction. This suggests that we should be using a sparse HashMap rather than a list over the full address space to represent balances.
For backwards compatibility, I kept the interface that allows creating the AccountState object from a continuous list and also kept the way we store …
> Refactoring account balances to be represented as a sparse HashMap

- README.md
- docker/rust/clone_solver.sh
- driver/src/price_finding/linear_optimization_price_finder.rs
Using the linear solver was broken (like everything that doesn't run as part of CI usually is), because the path from which the driver is run changed one up (when moving from rust projects to rust workspace).
I used this opportunity to adjust the repo to the new gitlab repo, add some explanation in the README and pin the repo against a version that we know works with the old prototype.
When running the stablecoin excange, we'll likely make the tag/rev an environment variable so it can be different for StableX and dƒusion.
Follow the steps in the readme to make sure the linear optimiser is giving good auction results (I ran the auciton e2e test to try it out).
> Fixing linear optimzer

- Cargo.lock
- driver/src/bin/main.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
This PR adds an optional fee parameter to the NaiveSolver. The logic is changed as follows:
1) We make "space" for the fee to be taken. This is we change the limit price to be more permissive. To achieve this we either require more stuff to be bought or less stuff to be sold (both would make the deal "better" for the user).
2) We do the matching logic as before
3) We post-process the volumes taking away the fees (increasing sellVolume if feeToken is sold, reducing buyVolume if fee token is bought)
```
Order {
account_id: 0,
sell_token: 0,
buy_token: 1,
sell_amount: 20000,
buy_amount: 9990,
},
Order {
account_id: 0,
sell_token: 1,
buy_token: 0,
sell_amount: 9990,
buy_amount: 19960,
},
```
Adjusted orders after step 1)
```
Order {
account_id: 0,
sell_token: 0,
buy_token: 1,
sell_amount: …
```
> Implement fee mechanism for naive solver

- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/flux.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/standing_order.rs
- dfusion_rust_core/src/models/util.rs
- driver/src/order_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/withdraw_driver.rs
- listener/src/event_handler/auction_settlement_handler.rs
- listener/src/event_handler/flux_transition_handler.rs
- listener/subgraph_definition/schema.graphql
- test/e2e-tests-auction.sh
- test/e2e-tests-deposit-withdraw.sh
- test/e2e-tests-standing-order.sh
This PR changes the data type of account_id from u16 to H160 (address type in solidity).
This is needed since in the StableX contract we don't compress the address space to 16 bits anymore.
Travis
> [Refactor] Make Accounts wide enough to hold addresses

- driver/src/contracts/stablex_contract.rs
- driver/src/driver/deposit_driver.rs
- driver/src/driver/order_driver.rs
- driver/src/driver/withdraw_driver.rs
- driver/src/error.rs
- driver/src/lib.rs
- driver/src/price_finding/naive_solver.rs
This change inmplements the `submit_solution` part of the StableX contract interface. For the purpose of simplified unit testing, two helper functions `encode_prices_for_contract` and `encode_execution_for_contract` are introduced to convert auction result data from the `<Order, Solution>` into a collection of vectors that the smart contract recognizes. 
A few new unit tests involving all possible corner cases to auction result parser are introduced. 
Test Plan: `cargo test`
> PoC submit solution

- dfusion_rust_core/src/models/util.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/util.rs
This useful function (previously only required by the `naive_solver`) will also come in handy in other places. throughout the driver (and possibly even the core) codebase.
I would have preferred to implement it more accurately as 
```js
impl From<u128> for U256 {
fn from(value: u128) -> U256 {
U256::from_big_endian(&x.to_be_bytes())
}
}
```
but I believe this requires a contribution to the ethereum-types repo (where U256 is defined). 
Note also I found a place in the code where we were using `U256::from_str` which does not seem to exist (an untested bug).
> move u128_to_U256 to util file and test on 1 and max.

- driver/src/price_finding/naive_solver.rs
- driver/src/util.rs
There were some issues with the NaiveSolver, which prevented the stableX e2e tests from working. Most importantly:
1) Price computation for `OrderPairType::BothFullyFilled` was inverted.
2) The rounding in `order_with_buffer_for_fee ` was done on the fee multiplier (.999 -> 1.0) instead of on the product of amount and fee leading to no reduction in the sell amount (and thus violating max. sell amounts when fee was added).
I interpreted this as a sign of poor unit tests and thus spent some time building more robust one:
First, I added a function that performs the validity checks of the smart contract (so that our tests can check that a solution will be accepted).
I then added unit tests for the three cases (left fully matched, right fully matched, both fully matched) that also work with …
> [NaiveSolver] bugfixes and more exhaustive unit tests

- driver/src/contracts/stablex_contract.rs
As discussed, we submit executed buy amounts to the smart contract which uniquely determines the sell amounts according to equation (2) from our discussion [here](https://github.com/gnosis/dex-contracts/issues/173#issuecomment-526163117)
This change refactors those (previously submitted) sell amounts to buy amounts. 
**Test Plan:** Cargo.
**NOTE** should not be merged before contracts are updated or, at the very latest before e2e testing is complete.
> [PoC] Submit Buy Amounts to StableX Contracts

- Cargo.lock
- driver/Cargo.toml
This, unused, `pairing` dependency was causing an "import error"
```
error[E0432]: unresolved import `byteorder`
--> driver/src/contracts/stablex_auction_element.rs:3:5
|
3 | use byteorder::{BigEndian, ByteOrder};
|     ^^^^^^^^^ help: a similar path exists: `pairing::byteorder`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `driver`.
```
Apparently, `pairing` also depends on `byteorder` so the compiler (even though it obviously knew) it was confused and crashed.
An attempt at removing the `byteorder` crate as a dependency and adjusting all imports to `use pairing::byteorder::ETC` resulted in a different failure.
**Solution** `pairing` was unused and removing it saved the day!
> [Cleanup] Remove Unused Dependency

- docker-compose.yml
- docker/rust/clone_solver.sh
- driver/src/contracts/stablex_contract.rs
- driver/src/driver/stablex_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/util.rs
- test/e2e-tests-stablex.sh
Right now our log output is pretty messy and verbose. This PR addresses it in the following way:
1. No longer log every 5 seconds that we have already applied the current batch
2. Don't invoke the solver on empty auctions (leading to some complaints in the solver)
3. Don't submit solutions that don't have any volume (and thus also no utility). That would just be waisting gas.
On top of that we update the smart contracts to not show the annoying error message about a Set not being readable before there are any entries.
Running the demo with the linear solver, will now show
```
stablex_1         |     Finished dev [unoptimized + debuginfo] target(s) in 0.23s
stablex_1         |      Running `target/debug/stablex`
stablex_1         | 2019-09-26 16:22:50,937 INFO  [driver::util] Using linear …
```
> [Stablex] Better driver logging

- driver/src/price_finding/naive_solver.rs
Trivial PR that justs removes the duplicate solution printing when using the naive solver. The stablex_driver already prints the found solution (for both naive as well as linear solver)
Run e2e demo in solver, see no duplicate printing of solution data.
> [Easy] Remove duplicate print statement

- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/solution.rs
- driver/src/driver/order_driver.rs
- driver/src/driver/stablex_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
As Felix mentioned in the other PR #269, our solution model is used in different contexts. Hence, it is appropriate to replace the name surplus with a more general name.
----
testplan:
unit tests
> [Easy] renaming surplus to objective value

- docker/truffle/Dockerfile
It turns out that `npm install` inside the docker image was not working due to the following error:
```
npm ERR! fatal: not a git repository: /app/dex-contracts/../.git/modules/dex-contracts
```
This was because we copy the git submodule dex-contracts into the docker container without its parent directory (cf. Dockerfile line 5). The `.git` file inside dex-contracts contains a pointer to its parent module which in the container does not exist (`/app/dex-contracts/../.git/modules/dex-contracts`).
This caused the error above.
I suggest to fix this by removing the git reference inside the container after copying the folder.
Inside dex-services, go into dex-contracts submodule and `rm -rf node_modules`. Back up in dex-services run `docker-compose build truffle` and see no errors.
> [Docker] fix truffle docker image

- docker/truffle/Dockerfile
- docker/truffle/run.sh
#280 excluded the git file in the truffle docker. However the command suggested doesn't actually copy the file structure as expected (it only copies all folders recursively but no top level files).
The reason things were still working are that we are always mounting the original dex-contracts repo as a volume in the docker container. Thus, removing the git file and most importantly doing any installation or injection are pointless.
This PR removes the unnecessary steps and makes sure we can actually run the migrations from within docker.
Note that it will still be required to run npm install locally before starting the container.
```
cd dex-contract && rm -rf build && cd ..
docker-compose build truffle
docker-compose up truffle
```
See no errors
> [Docker] fix truffle docker file

- driver/src/contracts/snapp_contract.rs
- driver/src/contracts/stablex_contract.rs
Gas is usually provided in GIGA wei. In our current implementation we set the gas price to a very small wei amount.
When testing solution submission on Rinkeby this turned out to be problematic (tx didn't get mined).
I'm not sure how this worked in the past.
Mined Rinkeby transaction with fix: https://rinkeby.etherscan.io/tx/0x20f6f26e0b2345e4be26080d6ee825f0c6143e07f0d10e184b9d43efb8a7f2af
Basically I created some orders between token 0 and 1 and made sure the service picks them up and applies a solution.
> [Easy] Fix gas price from WEI to GWEI

- dfusion_rust_core/src/lib.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/util.rs
- driver/src/util.rs
In order to ultimately calculate a solution's objective value we need to calculate the utility and disregarded utility per order. This PR implements those calculations.
This PR is the first part of the PR #281 as it was too big and got difficult to review.
Unit tests were added with and will be run on CI to verify calculations
> Add order utility and disregarded utility calculation

- docker/deploy.sh
This PR adds a call to an AUTODEPLOY url which will tell the AWS cluster that it has to restart our service (since there was a new deployment).
@davidalbela are you going to add the missing `AUTODEPLOY_URL` and `AUTODEPLOY_TOKEN ` secrets to our travis config?
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2F26n7937SwZkal2Oju%2Fgiphy.gif&token=pray" data-gitmeme-token="pray"><img src="https://media1.giphy.com/media/26n7937SwZkal2Oju/giphy.gif" title="Created by gitme.me with /pray"/></a>
> Adding webhook to deployment

- docker/deploy.sh
This new env is required as we want to set a different tag for the docker image than the one specified in the $TRAVIS_BRANCH
--
testplan: praying
> New env for auto deploying docker image

- docker/rust/clone_solver.sh
The solver crashed on rinkeby due to very small sellamounts
v0.3 of the solver has a fix for that.
> Integrating new solver version

- driver/src/price_finding/linear_optimization_price_finder.rs
[Easy] taking the `utilitlyPerOrder` out, as Tom's interface no longer support it
Without this fix, the integration of Tom's solver is no longer working. 
---
testplan:
```
docker-compose build --build-arg use_solver=1 stablex
docker-compose up stablex
npx truffle migrate
```
and run the e2e test. It is expected to fail, though you want to check in the driver console that prices were submitted succesfully
> [Easy] taking the `utilitlyPerOrder` out, as Tom's interface no longer support it

- Cargo.lock
- driver/Cargo.toml
- driver/src/driver/order_driver.rs
- driver/src/lib.rs
- driver/src/snapp.rs
Since the solver no longer calculates executed utility. Unfortunately this is required for computing the solution objective value which needs to be submitted with a solution for Snapp.
This PR is a first step to addressing this by calculating the Snapp objective value (the total executed utility of the orders) for submitting solutions.
This might help with #302 and with removing the `objective_value` field from the solution. This will also be nice for merging the two naive solvers together so it no longer needs to calculate this.
Unit tests.
> Add Snapp Objective Value Calculation

- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/order.rs
- dfusion_rust_core/src/models/solution.rs
- driver/src/driver/order_driver.rs
- driver/src/driver/stablex_driver.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/price_finding/snapp_naive_solver.rs
- driver/src/snapp.rs
Remove the solution objective value field as it is no longer used. We now calculate the Snapp objective value for submitting solutions to Snapp and we use the contract to evaluate the objective value in StableX.
This affects PR #302 and might cause merge conflicts. Depends on #304.
unit and e2e tests
> [Easy] Remove Solution Objective Value Field

- .travis.yml
- dfusion_rust_core/src/models/order.rs
This adds stricter linting by running `cargo fmt` on all workspace crates as well as running `cargo clippy` on all targets (including the `test` target, which we currently ignore) to check more code.
CI still passes
> [Easy] Stricter Linting

- README.md
- test/setup_contracts.sh
Let's use `npm ci` instead of `npm install` everywhere
CI
> [Easy] use npm ci instead of install

- .dockerignore
- .travis.yml
- README.md
- docker-compose.rinkeby.yaml
- docker-compose.yml
- docker/deploy.sh
This PR cleans up the `docker-compose.yml` file. At the moment, we have a bunch of very similar targets that have a complicated dependency structure:
```
,---- rust-service-development <-- stablex/driver/graph_listener
rust-service-basic  <-|
`---- rust-service-rinkeby <--- stablex-rinkeby
```
However, the build for rinkeby is the same as for ganache. All we really need is to use a different .env file. Continuing this pattern for other services and eventually mainnet will become very messy.
I believe using [multiple compose files](https://docs.docker.com/compose/extends/) is the better option as it allows to override specific values (e.g. the env file used).
Instead of running `docker-compose up stablex-rinkeby` we now specify the "base" config file and the override file
``` …
```
> Simplify docker compose setup

- .travis.yml
The Travis configuration uses `npm ci`, which deletes `node_modules` before installing from NPM cache. Therefore, caching `node_modules` is not really useful, and we should instead get Travis to cache the NPM cache in `~/.npm`.
None
> [Easy] Cache `.npm` Instead of `node_modules`

- Cargo.lock
- dfusion_rust_core/Cargo.toml
- driver/Cargo.toml
- listener/Cargo.toml
This oopsie was introduced in #336 
None - both are the same revision
> [Easy] Use `tag` Instead of `rev` For `graph-node-reader` Dependency

- Cargo.lock
- driver/Cargo.toml
:point_up: This is needed for `ethcontract-rs` because of conflicting transient build dependencies.
CI
> [Easy] Bump clarity from 0.1.8 to 0.1.23

- driver/src/contracts/stablex_auction_element.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/snapp.rs
- driver/src/util.rs
`U256` now provides conversion to and from `u128`. Use it instead of our own.
CI
> [Easy] Use `u128` Conversion

- .travis.yml
- docker/deploy.sh
Currently, we only deploy on master builds. We should do the same on tags. This will allow us to easily create deployments for different versions, even though the master branch train keeps on chugging.
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FBWQuTmejBHMaSP9LEp%2Fgiphy.gif&token=train_chugging" data-gitmeme-token="train_chugging"><img src="https://media2.giphy.com/media/BWQuTmejBHMaSP9LEp/giphy.gif" title="Created by gitme.me with /train_chugging"/></a>
> [Easy] Deploying images on tags

- .travis.yml
👆 
This should hopefully allow trades between tokens that don't have 18 decimals.
> [Easy] Bump dex-solver version 0.5

- .travis.yml
This change snuck in #363 but shouldn't have. This addresses that.
CI -> verify logs are dumped at end of rinkeby e2e test.
> Always log rinkeby e2e test logs

- docker/deploy.sh
Right now, we only restart the rinkeby AWS instance on master commits. This PR refactors the logic to allow for an array of autodeply URLs to be passed in (separated by semicolon).
This will allow us to restart both mainnet and rinkeby services on each master commit.
Printed the curl command locally. It remains to see bot services restart after this PR is merged in to master
> [Deploy] Allow multiple services to be restarted on master commit

- Cargo.lock
- driver/Cargo.toml
- driver/src/contracts/mod.rs
- driver/src/contracts/snapp_contract.rs
- driver/src/lib.rs
- driver/src/transport.rs
Adds a logging transport implementation that logs JSON RPC requests and results to assist debugging.
CI and take a look at the dumped rinkeby logs.
> Logging Transport

- driver/src/price_finding/linear_optimization_price_finder.rs
Hotfix for https://github.com/gnosis/dex-solver/issues/49
For some reason the solver does not always specify the execBuyAmount field. This PR makes it so that we assume it is 0 if we cannot find it on the json.
Updated unit tests.
> [Easy] Assume executed amount to be 0 if not in json result

- docker/deploy.sh
Reverts gnosis/dex-services#373
No longer needed, due to the fact that we can encode two target services in a single URL.
https://dfusion.auto.gnosisdev.com/services/dfusion-mainnet-master,dfusion-rinkeby-master/restart
> Revert "[Deploy] Allow multiple services to be restarted on master commit"

- .travis.yml
This surfaced after migrating from travis-ci.org to travis-ci.com as we are starting from a clean cache. We were not installing yarn dependencies in the e2e tests but instead relying on finding them in the cache.
CI
> [Fix Build] run yarn install in e2e tests

- .github/merge-when-green.yml
Given our long-running builds, I install ["merge when green"](https://github.com/phstc/probot-merge-when-green) which allows us to label a PR which will then get automatically merged as soon as travis is green (given prior approval).
This config makes it so that the commits will be squashed instead of the default (merged).
use label on this PR and see that commit gets squashed.
> Adding a merge when green config

- driver/src/logging.rs
This makes the logs more readable and easier to filter. Unfortunately it requires a bunch of boilerplate code just for adding the `record.module`.
```
DFUSION_LOG="info,driver=debug,dfusion_core=debug" cargo run --bin stablex
Dec 27 16:17:00.114 DEBG [driver::transport] sending request ID 0: {"jsonrpc":"2.0","method":"net_version","params":[],"id":0}
Dec 27 16:17:00.124 DEBG [driver::transport] request ID 0 completed with result: "5777"
Dec 27 16:17:00.124 INFO [stablex] Using contract at 0x419d…0c34
Dec 27 16:17:00.125 INFO [stablex] Using account 0x90f8…c9c1
...
```
> [Logging] Custom Format that prints module

- driver/src/contracts/stablex_contract.rs
:point_up: 
We were running into a gas limit on `eth_call` requests because the number of orders was getting too large.
See that the driver is no longer failing to get all orders on mainnet.
> remove gas limit for orders query

- .travis.yml
This should solve the problem of the solver not finding solutions in the presence of overlapping orders (e.g. last nights auction by Martin).
Observe tomorrow night's auction and expect a solution to be submitted.
> [Trivial] Bump solver version

- docker-compose.yml
Work around the issue reported here: trufflesuite/ganache-cli#706.
CI starts working again.
> [Easy] Use a fixed ganache CLI version to make workaround signed tx issue

- .travis.yml
We are seeing some flaky tests (e.g. [[1]](https://travis-ci.com/gnosis/dex-services/jobs/271235595) & [[2]](https://travis-ci.com/gnosis/dex-services/jobs/271380142)) which seem to stem from the fact that `~/.node-gyp/8.12.0/include/node/common.gypi` is empty where it should have a valid configuration inside. My hunch is that it is some kind of race condition with parallelising the build of the sha package and node-gyp.
This PR updates node to use the stable version we actually support (v10) and also the latest version of yarn. If this doesn't fix the issue, we likely have to enable verbose yarn logging to see in which order things are installed.
My hope is however that the issue is already fixed on the latest version.
CI and observing if we keep getting random failures.
> Use latest version of yarn and node10 for travis builds

- Cargo.lock
- listener/src/main.rs
PR #385 was accidentally merged without updating the Cargo.lock file to include the updated `graph-node-reader` tags. This PR addresses that.
We should consider failing the build if the Cargo.lock file is not in sync with the Cargo.toml file to avoid this in the future.
Build still passes.
> [Easy] Update Cargo.lock to reflect graph-node-reader tag

- .travis.yml
Closes #411 
Adding a command to the travis config that will fail if the lockfile was updated while building the project.
Change a version in the Cargo.lock, run tests. Then run
```
git diff --name-only | grep -q Cargo.lock
```
And see that exit code is not success.
> [Easy] check that Cargo lockfile is in sync

- docker/rust/Dockerfile
- e2e/tests/stablex_test.rs
Converting the e2e test that actually runs an entire auction on Rinkeby. It requires waiting for up to 5 minutes (depending on when the batch will finish), but other than the existing javascript test we  actually wait on the confirmations for deposits/and order placements making it more reliable than the one we have today.
It's not yet being used on travis, only locally
run 
```
docker-compose down && docker-compose -f docker-compose.yml -f docker-compose.rinkeby.yml up stablex
```
and then
```
cargo test -p e2e rinkeby -- --nocapture
```
and see the spectacle unfold...
> [E2E] StableX Rinkeby test in rust

- e2e/src/common.rs
- e2e/src/lib.rs
- e2e/src/stablex.rs
- e2e/tests/stablex_test.rs
This should help implementing the three e2e tests to test the SnappAuction contract while reusing the common pieces from the StableX tests. In particular this PR
- moves generated contract artifacts into top-level crate
- creates stablex.rs for methods related only to stablex (expecting a similar snapp.rs module to come)
- keeps the common part in common.rs and factoring the token generation, minting and approve logic out of the setup function into a separate function that can be reused for snapp e2e tests.
```
docker-compose down && docker-compose up stablex
(cd dex-contracts && npx truffle migrate)
cargo test -p e2e ganache
docker-compose down && docker-compose -f docker-compose.yml -f docker-compose.rinkeby.yml up stablex
cargo test -p e2e rinkeby -- --nocapture
```
> Refactoring components in the e2e project

- driver/src/driver/stablex_driver.rs
Closes #417 
The solver is running deterministically. Therefore, there is no point in calling it again with the same problem. Thus if it failed to produce a result, we may as well consider this batch as unsolvable.
I'd like to do the same for smart contract rejections. However, right now we can still have transient failures (e.g. 503 error from the full node) and thus it is not safe to rely on it. 
With an upgrade to ethcontracts we might be able to check for revert errors (and we should retry transient failures).
Added a unit test.
> Do not retry solving the instance if  failed

- README.md
The `graph-store-postgres` crate requires libpq to be installed or compilation will fail.
> Mention postgresql dependency

- dfusion_rust_core/src/models/account_state.rs
- dfusion_rust_core/src/models/solution.rs
- dfusion_rust_core/src/models/util.rs
- driver/src/contracts/stablex_contract.rs
- driver/src/driver/order_driver.rs
- driver/src/driver/stablex_driver.rs
- driver/src/price_finding/error.rs
- driver/src/price_finding/linear_optimization_price_finder.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/snapp.rs
- e2e/tests/stablex_test.rs
Reverts gnosis/dex-services#420
There is a case missed by all the existing tests. This is the proper handling of solution JSONS with prices containing `null` (which happens often). For example;
```
"prices": {
"token0": "1000000000000000000",
"token1": "9989999002997979320",
"token2": null,
},
```
TOdo - ensure e2e rinkeby test and unit test for `deserialize_result` handle this scenario.
> Revert "Use HashMap for Solution.prices"

- Cargo.lock
- driver/Cargo.toml
- driver/src/bin/stablex.rs
- driver/src/lib.rs
- driver/src/metrics/metrics_server.rs
- driver/src/metrics/mod.rs
This PR implements a basic Server to serve the Prometheus metrics we are going to collect to the central Prometheus server that is in charge of pulling them from all hosts.
Probably wouldn't technically require an entire thread of its own but since everything else is running on the main thread seams ok.
In the next PR I will actually add metrics
run stableX and see metrics being served under http://localhost:9586/
> [Prometheus] Implement a basic metrics server

- .travis.yml
This PR makes it so that build status failures and changes (when a failure changes back to green) are submitted to our oncall email address. @denisgranha can you let me know when the address is created?
After merging failing build see email notification being sent.
> Adding an oncall email to travis

- .travis.yml
- Cargo.lock
- driver/Cargo.toml
- driver/src/price_finding/linear_optimization_price_finder.rs
This is less error prone and less repetitive than managing the json by
hand.
We do not change which fields are handled.
We remove code handling both strings and numbers in parse_price_value
because these fields are always strings.
We remove some assertions of a specific error descriptions in favor of
only asserting the error kind. Error descriptions are human readable.
The code should not rely on specific strings.
> Use serde to (de)serialize the solver input and output json

- docker-compose.yml
- driver/src/bin/stablex.rs
- driver/src/driver/stablex_driver.rs
- driver/src/metrics/mod.rs
- driver/src/metrics/stablex_metrics.rs
Associated with #419 
This PR actually adds the metrics we are interested in. It hooks into the stablex driver to report relevant events such as starting auction processing (wrt. the time the batch was "released" for settlement), order fetching, price finding, etc.
Run service, open http://localhost:9586/ and see metrics such as
```
failures{stage="start"} 18
orders{type="orders"} 0
success{type="skipped"} 1
tokens{type="orders"} 0
users{type="orders"} 0
```
> Recording Metrics for StableX

- docker-compose.yml
- listener/subgraph_definition/dfusion
This PR updates to the most recent released contracts.
The older version 0.1.3 will still be driven by separate AWS jobs for the next couple of days/weeks until it is fully deprecated.
CI and afterwards trying a first trade on the new version.
> Update dex-contract to 0.2.0

- driver/src/logging.rs
When there is a lot of logging happening, we can see "channel overflow" errors (cf. [here](https://logs.gnosisdev.com/goto/a859e0d7fbe28cf3daba1c924bbc2c8c))
This can be mitigated by setting a larger channel size (the default is 128). I'm not sure if 1kb is sufficient, but we can observe and adjust.
Expect to see no more channel overflow errors.
> [Easy] increase async logger buffer size

- .travis.yml
This reverts commit 696046d1e1adf1121755ee7d9597c77db0879ff7.
> Revert "[Trivial] Bump solver to v0.5.7 (#461)"

- e2e/src/common.rs
I assume this is the reason for #467 
We are not actually waiting on moving the time forward and thus might end up calling `evm_increaseTime` more than once in parallel, which is likely not going to increase the time twice. Thus we are getting stuck at an old time and do not observe any state transitions. 
Cf. e.g. that in the failing tests, the solver is waiting for the auction 0's bidding phase to end:
```
driver_1_a5e41de77ffa | Jan 30 02:47:43.042 INFO [driver::contracts::snapp_contract] objective value: 0
driver_1_a5e41de77ffa | Jan 30 02:47:48.312 INFO [driver::driver::order_driver] Already bid for auction slot 0
driver_1_a5e41de77ffa | Jan 30 02:47:53.445 INFO [driver::driver::order_driver] Already bid for auction slot 0
driver_1_a5e41de77ffa | Jan 30 02:47:58.576 INFO …
```
> [Easy] Wait on time forwarding future in e2e test

- driver/src/bin/stablex.rs
- driver/src/driver/stablex_driver.rs
- driver/src/lib.rs
- driver/src/orderbook/mod.rs
- driver/src/solution_submission/mod.rs
This PR adds a layer of abstraction between the StableX driver and StableX contract. In particular, it separates the potential interactions in reading (OrderBookReading trait) and writing (SolutionSubmitting trait).
This allows us to implement more sophisticated logic for the two (e.g. an order book reader based on the graph instead of the contracts, a paginated reader, a reader that is using a blacklist of users or tokens, etc.) and decouples the driver from the smart contract.
In the next step I will implement a FilterinOrderBookReader that reads a blacklist from an environment variable.
Most of the added lines is boilerplate code. In particular I will look into replacing our mocking framework into something less verbose.
Unit test.
> Decoupling the StableX contract and driver

- driver/src/driver/stablex_driver.rs
This was causing the driver to get "out of sync" with batches. More detailed description of the issue is found here: #475 
This PR is a temporary solution to the issue, in the long run a solution where we have separate threads for each batch that gets cancelled once the batch submission time is up might be a more robust solution.
New unit test.
> Do not run solver if previous solution validation and submission failed.

- README.md
- common.env
- driver/src/bin/stablex.rs
- driver/src/orderbook/filtered_orderbook.rs
- driver/src/orderbook/mod.rs
Implements #432 
This PR adds another implementation of the orderbook that allows filtering specific orders based on a config string currently passed in via an environment variable.
It mainly allows for three types of filters
- malicious/fake tokens (ignore all orders that have a certain token ID in buy or sell token)
- malicious users (ignore all orders from users with certain addresses)
- malicious orders (ignore specific pairs of user + order id)
The driver is now wired to an orderbook filter, which itself uses a regular on chain order book reader as a source of truth. The source of the filter could theoretically be changed to a off-chain orderbook reader or a paginated reader in the long term.
Added unit tests.
> Implementing a blacklist for the order book

- driver/src/price_finding/linear_optimization_price_finder.rs
This `instances` directory will be mounted on our AWS instance so that the data can persist across restarts.
First step towards #478 
Make sure linear solver is still running on e.g. rinkeby
> [Easy] write instance files into own directory

- common.env
- driver/src/bin/stablex.rs
The PR https://github.com/gnosis/dex-services/pull/476 is currently throwing errors in production.
Due to the fact, that we do not set the env: ORDERBOOK_FILTER, the code runs the fallback and sets ORDERBOOK_FILTER=""; Due to this, we are receiving the following error: 
`ERRO [stablex] Error parsing orderbook filter: EOF while parsing a value at line 1 column 0`
This PR changes the fallback for the env from "" to "{}". Now the parsing is fine and we don't get any error logs.
We could have also set ORDERBOOK_FILTER in production, but I would prefer this fallback solution to work.
> [Fix Orderbook filter] No longer requiring the ODERBOOK_FILTER env to be set

- Cargo.lock
As of rust 1.41.0, there is a new cargo lock format that is less prone to merge conflicts: https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#less-conflict-prone-cargolock-format
CI
> Update to new cargo lock format

- Cargo.lock
- e2e/Cargo.toml
Remove some graph dependencies in the e2e test crate that were required for snapp but are no longer used.
CI
> [Easy] Remove graph dependencies in e2e test crate

- package-lock.json
This PR removes a stray and mostly empty `package-lock.json` file that managed to sneak past all of us.
None
> [Trivial] Remove stray `package-lock.json` file

- driver/Cargo.toml
Specify `rustc-hex` version, it was the only dependency without one. Note that this does not change the version being used - the `Cargo.lock` file is unchanged.
CI
> [Trivial] Specify version for rustc-hex

- .travis.yml
#485 removed caching including `node-gyp` cache. Adding it back in as I saw some intermittent build failures tonight that were corrected by a re-build.
It would be nice to understand exactly why this error is happening and fix the root cause.
Here is an example failure: https://travis-ci.com/gnosis/dex-services/builds/147873838#L320
See if intermittent failures go away.
> [Easy] Cache node-gyp

- Cargo.lock
This PR is the result of a `cargo update` to update some transient dependencies not being bumped by dependabot.
The full list of updates are:
```
Updating arrayref v0.3.5 -> v0.3.6
Removing backtrace v0.3.43
Removing backtrace-sys v0.1.32
Adding base64 v0.11.0
Updating blake2b_simd v0.5.9 -> v0.5.10
Updating constant_time_eq v0.1.4 -> v0.1.5
Removing failure v0.1.6
Removing failure_derive v0.1.6
Updating indexmap v1.3.1 -> v1.3.2
Updating num-integer v0.1.41 -> v0.1.42
Updating num-traits v0.2.10 -> v0.2.11
Updating protobuf v2.8.1 -> v2.10.1
Updating redox_users v0.3.1 -> v0.3.4
Updating rust-argon2 v0.5.1 -> v0.7.0
Removing rustc-demangle v0.1.16
Removing synstructure v0.12.3
```
Alternatively, we can create one PR for each update.
CI
> [Easy] Update transient dependencies

- driver/src/price_finding/optimization_price_finder.rs
Closes #473 
Requested by @twalth3r .
I'm making this an implementation detail of the serialisation logic as it doesn't seem as if it has to be enforced on a higher level.
Added a unit test. 
Also checked an instance files after running the mainnet solver by running:
```
docker-compose down && docker-compose -f docker-compose.yml -f docker-compose.mainnet.yml run stablex bash
cargo run --bin stablex
cat instances/*
```
> Sort tokenIds and filter out 0 balances

- driver/src/contracts/stablex_auction_element.rs
- driver/src/contracts/stablex_contract.rs
- driver/src/models/mod.rs
- driver/src/models/order.rs
- driver/src/orderbook/filtered_orderbook.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/optimization_price_finder.rs
And replace it with `id`. This was a hack to deal with snapp/stablex differences that is no longer needed.
CI
> Remove `BatchInformation` from order

- driver/src/contracts/mod.rs
- driver/src/contracts/stablex_contract.rs
Closes #369 
With the update to ethcontract-rs 0.3.0 we can use the estimated gas amount and price (with a factor to ensure we are getting fast execution speed).
This should prevent us from drastically overpaying tx fees by using a fixed gas price of 20GWEI (the avg. solution submission costs between 5-10$ atm). We will now be using 3x the avg. gas price. At the time of testing this was about 3x6GWEI
E2E tests, check submission times as soon as it's in staging.
Get average gas price (in hex) from full node:
```
curl -H "Content-type:application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":7398897897897}' https://node.mainnet.gnosisdev.com
```
> Use estimated gas amount and price

- README.md
When attempting to run the optimizing solver on mainnet I was getting import errors in the python code. I noticed that we use `master` in gnosis-staging while the readme uses `latest`. Changing to `master` fixed my issue but I am not sure what this change actually means.
> Use master instead of latest for SOLVER_BASE

- driver/src/metrics/stablex_metrics.rs
Requested by @luarx 
This is needed as metric names need to be globally unique in our entire network. A general name like success is not really serving this purpose.
Run locally and see new test names showing up on `http://localhost:9586/`
> [Trivial] prefixing prometheus metrics

- .travis.yml
as title. The new version addresses this issue: https://github.com/gnosis/dex-solver/issues/131
CI
> [Easy] Bump solver version

- docker-compose.binary.yml
- docker-compose.yml
- docker/rust/Dockerfile
This allows for changes to the local filesystem to be directly reflected in the docker container without having to rebuild the entire container. It makes testing changes in a docker setup much faster.
- docker-compose up stablex
- Make a change inside the driver code
- stop and restart the container
- see change is reflected without having had to docker-compose build.
> [Easy] sync src code between local and docker filesystem

- Cargo.lock
- Cargo.toml
- driver/Cargo.toml
- driver/src/contracts/mod.rs
- driver/src/contracts/stablex_auction_element.rs
- driver/src/contracts/stablex_contract.rs
- driver/src/driver/stablex_driver.rs
- driver/src/error.rs
- driver/src/main.rs
- driver/src/metrics/stablex_metrics.rs
- driver/src/models/account_state.rs
- driver/src/models/order.rs
- driver/src/orderbook/filtered_orderbook.rs
- driver/src/orderbook/mod.rs
- driver/src/orderbook/paginated_auction_data_reader.rs
- driver/src/price_finding/naive_solver.rs
- driver/src/price_finding/optimization_price_finder.rs
- driver/src/solution_submission/mod.rs
- driver/src/transport.rs
- driver/src/util.rs
- e2e/Cargo.toml
- e2e/src/common.rs
- e2e/src/stablex.rs
- e2e/tests/stablex_test.rs
This PR upgrades to use the most recent version of the crates.io `ethcontract` crate. This means we will no longer have to maintain the special compatibility branch for `dex-services`. Because of this update, the version of some of the shared dependencies have changed, and the generated contract bindings use the correct primitive integer types (no longer coerced to `u64`, `U128` and `U256`). This PR:
- Updates code to use re-exported `web3` and `jsonrpc_core` crates, reducing the dependency update burden in `dex-services`
- Updates code to use the correct contract primitive integer types. Specifically, there are no more `u16` to `u64` and `u128` to `U128` conversions.
The main benefit of this update is that:
- Dependabot will automatically create PRs when ethcontract updates again
- No …
> Upgrade to crates.io ethcontract

- driver/src/transport.rs
Timeout errors currently show up like this:
> ERROR (pod: dev-dfusion-mainnet-fallback-solver-master-cc98769b8-djgr4): 
Feb 17 17:11:41.702 WARN [isahc::handler] request completed with error [id=AtomicCell { value: 0 }]: Timeout: request took longer than the configured timeout
Note, that id is not actually populated. This comes from the isahc repo https://github.com/sagebind/isahc/blob/eb2d1c04b60b2d1783e3e6d978c14a788459fd48/src/handler.rs and is likely a bug in their code (I wasn't able to figure it out at first glance and am a bit swamped to spend a lot of time reproducing).
This PR makes it so that we print a warning in our module which allows to surface the ID properly. We shouldn't be relying on external warnings anyways.
- run the container
- disconnect from the internet
- see …
> [Easy] Print failing request ID when we time out

- .travis.yml
- common-mainnet.env
- common-rinkeby.env
- driver/src/main.rs
- driver/src/price_finding/mod.rs
- driver/src/price_finding/optimization_price_finder.rs
- driver/src/price_finding/price_finder_interface.rs
- driver/src/util.rs
The current choices between the optimization models MIP and NLP are not good, as the benchmarks have shown that NLP kind of always underperforms MIP.
This PR implements a real fallback solver: which uses as well the MIP and price feed queried by the solver.
Later on, we will use the query price feeds from the driver, this is really just an intermediate step for the trading challenge this evening.
The PR https://gitlab.gnosisdev.com/devops/gnosis-staging/merge_requests/181
does the necessary changes in the deployment configs 
---
testplan:
```
T1: docker-compose build --build-arg SOLVER_BASE=163030813197.dkr.ecr.us-east-1.amazonaws.com/dex-solver:v0.5.11 stablex
```
put SOLVER_TYPE=fallback-solver into common.env
```
docker-compose up stablex
T2: cargo test -p e2e ganache -- --nocapture …
```
> First draft of fallback and standard solver

- README.md
- driver/src/main.rs
- driver/src/price_finding/optimization_price_finder.rs
- driver/src/price_finding/price_finder_interface.rs
- No longer receiving external price info via solver 
- Updating documentation and a small renaming of the env PRICE_INFORMATION to TOKEN_DATA.
> [Easy] No longer receiving external price info via solver && clean up for token_data

- .travis.yml
- driver/src/price_finding/price_finder_interface.rs
This solver bump has a fix for:
https://github.com/gnosis/dex-solver/issues/182
and completely eliminates the price fetching by the solver.
> Solver bump to v0.5.18 (price aggregator fix and using only driver prices)

- driver/src/solution_submission/mod.rs
Addresses #663
By running the "verify objective value" call against pending blocks we should not run into timing issues as the pending block should be closer to the actual time of the block that will be mined next.
Unit tests, plus observing if we are no longer running into the related issue.
> [Easy] use pending block for verifying objective value

- .travis.yml
- docker-compose.binary.yml
- docker-compose.open-solver.yml
- docker-compose.private-solver.yml
I just realized that https://github.com/gnosis/dex-services/pull/680 kept the unnecessary `docker-compose.binary` file. 
Since we are introducing the `docker-compose.private-solver.yml` and `docker-compose.open-solver.yml`, which store the images `stablex-binary-private` and `stablex-binary-public`, there was no need to keep `docker-compose.binary.yml`. I forgot to remove it.
Sorry, for the late clean up
> Removing docker-compose.binary

- Cargo.lock
This PR just does a `cargo update` to update some of the transient dependencies that are not getting picked up the dependabot that I noticed from #719.
CI as a smoke test to make sure everything is still working. Otherwise there are no code changes.
> [Easy] Cargo update

- docker/rust/Dockerfile
The `pricegraph` crate and directory are now part of the workspace but were not getting copied to the docker build image. This PR addresses that.
> Add pricegraph directory to the docker image build

- driver/src/contracts/stablex_auction_element.rs
Suggested in https://github.com/gnosis/dex-services/pull/748#discussion_r413044891
unit test has this code covered.
> [Trivial] Use copy_from_slice instead of iterating over buffer

- .travis.yml
This PR increases the solver version from v0.7.1 to v0.7.2. 
Fixes https://github.com/gnosis/dex-solver/issues/261 (invalid JSON in solution file)
---
> [Easy] Bump solver version to v0.7.2

- pricegraph/src/orderbook.rs
Because of how the pricegraph was previously structured, the projection graph needed to be updated before calling methods that did path searching. This has not been the case for a while now, but the method was left in.
CI, and unit tests still pass. Additionally, we can test with an actual orderbook and a real price estimate:
```
$ cargo test -p pricegraph real_orderbooks -- --nocapture # before change
Compiling pricegraph v0.1.0 (/var/home/nlordell/Developer/dex-services/pricegraph)
Finished test [unoptimized + debuginfo] target(s) in 1.41s
Running /var/home/nlordell/Developer/dex-services/target/debug/deps/pricegraph-397047f497bad3b3
running 1 test
#5298183: estimated price for selling 1 WETH at 194.87633796952346 DAI/WETH
test orderbook::tests::real_orderbooks ... ok
$ cargo test -p …
```
> [Pricegraph] Remove unused method

- core/src/contracts/stablex_contract.rs
- core/src/contracts/stablex_contract/search_batches.rs
Fixes #832.
Implements a faster algorithm to determine the last block of a batch based on binary search.
This is a rewrite of PR #904. The logic is mostly unchanged but the structure, based on @fleupold's comments, is very different. There is now
- a trait `BatchIdRetrieving` implemented for `web3` that yields information on batch ids.
- a generic function implementing binary search for the last block of a batch that relies on the implementation of `BatchIdRetriever`.
`BatchIdRetriever` is not tested. The function implementing binary search is tested over a mock structure implementing `BatchIdRetriever`.
Compared to the older method, it makes more web3 calls for 2 and 4 steps back.
```
before:  1 2 3 4 5  6  7  8  9 10 11 12 13 14 15 16...
now:     1 3 3 5 5  5  5  7  7  7  7  7  7  7  7 …
```
> Efficient last block for batch bis

- .travis.yml
This version contains another speed-up PR for finding the best cycle in the best-ring-solver:
https://github.com/gnosis/dex-solver/pull/287
e2e tests
> Bump solver version to v0.7.5

- .travis.yml
- core/src/price_finding/price_finder_interface.rs
This PR:
* passes the `--optModel` parameter to the private solvers (standard and best-ring)
* uses the two-stage model for the standard solver (see https://github.com/gnosis/dex-solver/pull/296)
* updates the solver version to v0.7.7
e2e tests
> Use two-stage model for standard solver

- core/src/price_finding/price_finder_interface.rs
This PR changes the optimization model used in the best-ring-solver from MIP to two-stage. The two-stage model seems to be numerically more stable, which will hopefully avoid many of the `invalid execution request` errors (while returning the same solutions in almost all cases).
e2e tests
> Use two-stage model in BestRingSolver.

- core/src/token_info.rs
- core/src/token_info/cached.rs
- price-estimator/README.md
- price-estimator/src/filter.rs
- price-estimator/src/main.rs
- price-estimator/src/models.rs
and add error code handling of rejections
First step for #1082 . So far this commit only implements this for one route but not the others. If this way of implementation makes sense I will add it to the other routes (should it apply to all routes, even `/marktets`?) and update the readme. Then we probably also want the token info overrides like the driver has for tokens that don't implement ERC20 properly.
Unit test for error codes and manual test:
```
$ curl "localhost:8080/api/v1/markets/4-7/estimated-buy-amount/1000000000000000000?atoms=true"
{"baseTokenId":"4","quoteTokenId":"7","buyAmountInBase":"1006194.8387101036","sellAmountInQuote":"1000000000000000000"}
$ curl "localhost:8080/api/v1/markets/4-7/estimated-buy-amount/1?atoms=false" …
```
> Implement atoms=false for estimated_buy_amount

- pricegraph/src/api.rs
- pricegraph/src/api/price_estimation.rs
- pricegraph/src/api/transitive_orderbook.rs
- pricegraph/src/lib.rs
- pricegraph/src/num.rs
- pricegraph/src/test.rs
This PR just splits the `Pricegraph` `impl` blocks into multiple submodules. The ultimate plan is to lift `Orderbook` methods into the `Pricegraph` type (for computing transitive orderbooks and price estimates) so that the `Orderbook` type only contains primitives for manipulating the orderbook graph while the `Pricegraph` type actually computes things by combining these primitives.
This is in an effort to reduce the size of `orderbook.rs` which is currently >1000L long :disappointed:. The motivation for splitting operations into their own modules is to allow the `Pricegraph` API surface to grow without creating another run-away module with way too much code that becomes hard to navigate.
In the following PRs, I plan on:
- move `Orderbook::{reduce_overlapping_transitive_orderbook, …
> Separate API operations into modules

- .travis.yml
This solver bump includes:
* make writing intermediate/auxiliary output files optional (and deactivate by default): https://github.com/gnosis/dex-solver/pull/321
* deactivate economic viability constraint in first stage of the two-stage model: https://github.com/gnosis/dex-solver/pull/324
> Increase private solver version to v0.8.3

- core/src/driver/scheduler/system.rs
The async fn should not be using wait(). Crashes because it is not
allowed to wait() in a future that is itself wait()ed.
[Optional] 
Fixes #issue
*<Context of what this change does, why it is needed and how it is accomplished>*
*<Explain how you and a reviewer have/intend to test this change>*
> Fix panic caused by wait() instead of await

- Cargo.lock
- core/Cargo.toml
- core/src/contracts/stablex_contract.rs
- core/src/driver/scheduler.rs
- core/src/driver/scheduler/evm.rs
- core/src/driver/scheduler/system.rs
- core/src/driver/stablex_driver.rs
- core/src/orderbook/onchain_filtered_orderbook.rs
- core/src/orderbook/paginated_orderbook.rs
- core/src/orderbook/streamed/updating_orderbook.rs
- core/src/price_finding.rs
- core/src/solution_submission.rs
- core/src/solution_submission/retry.rs
- driver/src/main.rs
This involves converting several structs to store Arcs instead of references. This is more code in terms of lines but also simplifies lifetimes so imo it's an improvement.
CI and `cargo test -p core system::tests::test_real -- --ignored --nocapture`
> Replace crossbream scoped thread with asycnstd task

- .travis.yml
The solver bumps incorporate the stronger economic viability restriction for solution:
Every individual order (except those that sell OWL) now needs to contribute a certain amount of fees (by, default, the same value as passed as `--minAvgFeePerOrder` is used).
> Bump private and open solver

- e2e/README.md
This PR adds some documentation for running the e2e `pricegraph` scripts.
@fedgiac is going to try it out!
> Add e2e script docuemtnation

- pricegraph/src/graph/shortest_paths.rs
- pricegraph/src/orderbook.rs
This PR adds a new failing test similar to #1370 except triggered with an actual orderbook instead of one created directly on a `petgraph::Graph` as well as a `panic` to prevent the service from running out of memory in these cases. This will be addressed in #1370 and #1374 at which point the `#[should_panic]` can be removed.
This is just a band-aid to make it so the services don't restart in case we hit these rounding issues as a bandaid fix while the true fix is being worked on.
Added assert and new unit test covering it.
> Panic intead of endlessly allocating.

- services-core/src/metrics/solver_metrics.rs
This will help us to measure one of our goals ("Batches with non trivial solutions in which Standard Solver (using Gurobi), Best Ring Solver (using SCIP) and Open Solver finish without interruption before time limit").
At the moment this could be inferred by the optimality gap (close to 0 meaning solved to optimality, but it's not entirely clear what the right threshold is, therefore I think it's easy enough to add this metric as an explicit counter.
Here is an example instance that was interrupted because it ran out of time: https://gnosis-dev-dfusion.s3.amazonaws.com/data/rinkeby_dev/standard-solver/results/2020-10-04/instance_5339384_2020-10-04T12%3A45%3A30.550230225%2B00%3A00/06_solution_int_valid.json
Run:
```
cargo run --bin driver -- --node-url …
```
> Record a metric for when the solver ran out of time

- .travis.yml
Includes a small fix by @marcovc to the handling of timeouts: https://github.com/gnosis/dex-solver/pull/335
> Bump private solver to v0.8.5

- Cargo.lock
- pricegraph/bench/Cargo.toml
- pricegraph/bench/pricegraph.rs
This PR adds benchmarks for the added bounded bellman ford implementation. I only added it to the transitive orderbook computation as this seems to be the most expensive operation anyways
`cd pricegraph/bench && cargo bench`
> Add Benchmarks for bounded bellman ford

- .travis.yml
Solver bump includes an upgrade of Gurobi from 9.0.1 to 9.1.0
> Bump private solver version to v0.8.6

- driver/docker/rust/Dockerfile.debug
- services-core/src/solution_submission/retry.rs
This is the final PR and should pass CI.
New unit tests, CI.
> Cancellation refactor 4: Update tests for the new retry-cancellation api

- services-core/src/solution_submission.rs
Fixes alerts we have seen twice today in dev channel.
If the result of a Cancellation/Solution submission is not an err, it was mined. At the moment it returns false in that case leading to successful txs not being recognized up by the system.
Will add a unit test.
> [Easy] Fix inverted logic in was_mined()

- .travis.yml
Contains https://github.com/gnosis/dex-solver/pull/338 which prunes the result JSON to only contain information relevant to the solution (i.e., no untouched-token prices, no accounts that didn't trade).
> Bump private solver to v0.8.7

- .travis.yml
This PR pins the Rust version to `1.49.0` instead of `stable`. Since this repo is no longer actively developed, it avoids unexpectedly CI and deployments on Clippy lints.
CI starts passing again.
> Pin Rust version

- Cargo.lock
- contracts/Cargo.toml
- contracts/build.rs
- driver/Cargo.toml
- e2e/Cargo.toml
- e2e/src/common.rs
- price-estimator/Cargo.toml
- pricegraph/Cargo.toml
- pricegraph/data/bin/Cargo.toml
- services-core/Cargo.toml
- services-core/src/orderbook/filtered_orderbook.rs
This PR addresses an alert we are seeing with the latest geth nodes that by default do not contain tx inclusion logs for more than one year. Since our GPv1 Settlement contract was deployed more than a year ago, we run into issues fetching all events (which tries to get the block number from the deployment tx).
We fix this by manually specifying the block numbers for the the three main deployments:
- https://etherscan.io/tx/0xe74e8e965afc67f96a38caee794f008be33a7fe7ea96b9baad7b2963250ac36a
- https://rinkeby.etherscan.io/tx/0xc5bf4f48747093a79b623c2a2392ccbdb73a3d788e7d1f0f53f640ea18496d90
- https://blockscout.com/xdai/mainnet/tx/0xd5e7da686ace1ae7f1917ad54b8610ee936bdc900e56b495739795fba3d5e7c1/internal-transactions
Due to some version incompatibilities stemming from the new ethcontract-rs …
> Use custom GPv1 deployement block

- .travis.yml
This update introduces a MIN_TIME_LIMIT constant that is set to 30 seconds. If the time limit that is passed to the solver is below that value, the solver immediately returns the trivial solution. This is to address https://github.com/gnosis/dex-solver/issues/341.
> Bump private solver to v0.8.8
